<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC (c) 2004-2018
 *
 * Generated from /home/dev/buildkit/build/dmaster/sites/default/files/civicrm/ext/civicrm-advanced-events/xml/schema/CRM/AdvancedEvents/EventTemplate.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:0f347e84a0b30cf7d4fed56b57ce1753)
 */

/**
 * Database access object for the EventTemplate entity.
 */
class CRM_AdvancedEvents_DAO_EventTemplate extends CRM_Core_DAO {

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  static $_tableName = 'civicrm_event_template';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  static $_log = TRUE;

  /**
   * Unique EventTemplate ID
   *
   * @var int unsigned
   */
  public $id;

  /**
   * FK to Event
   *
   * @var int unsigned
   */
  public $event_id;

  /**
   * FK to Event
   *
   * @var int unsigned
   */
  public $template_id;

  /**
   * Event Template Title
   *
   * @var string
   */
  public $title;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_event_template';
    parent::__construct();
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static ::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'event_id', 'civicrm_event', 'id');
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'template_id', 'civicrm_event', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => 'Unique EventTemplate ID',
          'required' => TRUE,
          'table_name' => 'civicrm_event_template',
          'entity' => 'EventTemplate',
          'bao' => 'CRM_AdvancedEvents_DAO_EventTemplate',
          'localizable' => 0,
        ],
        'event_id' => [
          'name' => 'event_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => 'FK to Event',
          'table_name' => 'civicrm_event_template',
          'entity' => 'EventTemplate',
          'bao' => 'CRM_AdvancedEvents_DAO_EventTemplate',
          'localizable' => 0,
        ],
        'template_id' => [
          'name' => 'template_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => 'FK to Event',
          'table_name' => 'civicrm_event_template',
          'entity' => 'EventTemplate',
          'bao' => 'CRM_AdvancedEvents_DAO_EventTemplate',
          'localizable' => 0,
        ],
        'title' => [
          'name' => 'title',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Event Template Title'),
          'description' => 'Event Template Title',
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'import' => TRUE,
          'where' => 'civicrm_event_template.title',
          'headerPattern' => '/(template.)?title$/i',
          'dataPattern' => '',
          'export' => TRUE,
          'table_name' => 'civicrm_event_template',
          'entity' => 'EventTemplate',
          'bao' => 'CRM_AdvancedEvents_DAO_EventTemplate',
          'localizable' => 1,
          'html' => [
            'type' => 'Text',
          ],
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return CRM_Core_DAO::getLocaleTableName(self::$_tableName);
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'event_template', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'event_template', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
